# Generated by Django 5.0.2 on 2024-02-13 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Место выполнения привычки')),
                ('time', models.DateTimeField(verbose_name='Дата и время, когда необходимо выполнять привычку')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('periodicity', models.CharField(choices=[('1', 'ежедневно'), ('2', 'раз в два дня'), ('3', 'раз в три дня'), ('4', 'раз в четыре дня'), ('5', 'раз в пять дней'), ('6', 'раз в шесть дней'), ('7', 'раз в неделю')], default='1', max_length=30, verbose_name='Переодичность привычки')),
                ('award', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вознаграждение за выполнение привычки')),
                ('time_to_complete', models.SmallIntegerField(verbose_name='Время на выполнение привычки')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_habit', to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
